const URL='https://gpukluiksejdpbbtiyze.supabase.co';const KEY='sb_publishable_qvM58njlnFC00YXyfIE0k_uvI1Dbf3';const db=window.supabase.createClient(URL,KEY);
let mode='login',user=null,me=null,people=[],tasks=[];
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), manager=()=>['Quản trị viên','Chỉ huy'].includes(me?.role), norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
async function profile(u){let r=await db.from('qlcv_profiles').select('*').eq('id',u.id).maybeSingle();if(r.error)throw r.error;if(r.data)return r.data;let name=u.user_metadata?.full_name||u.email?.split('@')[0]||'Cán bộ';let x=await db.from('qlcv_profiles').insert({id:u.id,full_name:name}).select().single();if(x.error)throw x.error;return x.data}
async function load(){let a=await db.auth.getUser();if(!a.data.user)return showAuth();user=a.data.user;try{me=await profile(user);let [p,t]=await Promise.all([db.from('qlcv_profiles').select('*').order('full_name'),db.from('qlcv_tasks').select('*').order('created_at',{ascending:false})]);if(p.error)throw p.error;if(t.error)throw t.error;people=p.data||[];tasks=t.data||[];showApp();render()}catch(e){console.error(e);$('authMsg').textContent=e.message}}
function showAuth(){$('auth').classList.remove('hidden');$('app').classList.add('hidden')}function showApp(){$('auth').classList.add('hidden');$('app').classList.remove('hidden')}
function render(){ $('welcome').textContent='Xin chào '+(me.full_name||'');$('role').textContent=me.role;$('pName').value=me.full_name||'';$('pUnit').value=me.unit||'';$('pPhone').value=me.phone||'';$('pRole').textContent=me.role;$('newTask').classList.toggle('hidden',!manager());let a=tasks.length,b=tasks.filter(x=>x.status==='Chưa bắt đầu').length,c=tasks.filter(x=>x.status==='Đang thực hiện').length,d=tasks.filter(x=>x.status==='Đã hoàn thành').length,e=tasks.filter(x=>x.status==='Quá hạn').length;['sAll','sTodo','sDoing','sDone','sLate'].forEach((id,i)=>$(id).textContent=[a,b,c,d,e][i]);renderTasks()}
function renderTasks(){let q=norm($('search').value),s=$('status').value,p=$('priority').value;let list=tasks.filter(t=>(!q||norm([t.title,t.description,t.task_group,t.status,t.priority].join(' ')).includes(q))&&(!s||t.status===s)&&(!p||t.priority===p));$('count').textContent=list.length+' công việc';if(!list.length){$('tasks').innerHTML='<div class="task">Chưa có công việc phù hợp.</div>';return}$('tasks').innerHTML=list.map(t=>{let person=people.find(x=>x.id===t.assignee_id),can=manager()||t.assignee_id===user.id,cl=t.status==='Đã hoàn thành'?'done':t.status==='Đang thực hiện'?'doing':t.status==='Quá hạn'?'late':'';return '<article class="task"><div class="taskTop"><div><div class="taskTitle">'+esc(t.title)+'</div><div class="desc">'+esc(t.description)+'</div></div><span class="chip '+cl+'">'+esc(t.status)+'</span></div><div class="chips"><span class="chip">'+esc(t.task_group)+'</span><span class="chip '+(t.priority==='Khẩn'?'urgent':'')+'">'+esc(t.priority)+'</span><span class="chip">Hạn: '+(t.due_date?new Date(t.due_date+'T00:00:00').toLocaleDateString('vi-VN'):'Chưa đặt')+'</span></div><div class="bar"><i style="width:'+Math.max(0,Math.min(100,t.progress||0))+'%"></i></div><div class="taskBottom"><span>Thực hiện: <b>'+esc(person?.full_name||'Chưa phân công')+'</b> · '+(t.progress||0)+'%</span><span>'+ (can?'<button onclick="openUpdate(\''+t.id+'\')">Cập nhật</button> ':'')+(manager()?'<button onclick="removeTask(\''+t.id+'\')">Xóa</button>':'')+'</span></div></article>'}).join('')}
window.openUpdate=id=>{let t=tasks.find(x=>x.id===id);if(!t)return;$('uId').value=id;$('uStatus').value=t.status;$('uProgress').value=t.progress||0;$('uLabel').textContent=(t.progress||0)+'%';$('uNote').value='';$('updateModal').classList.remove('hidden')};
window.removeTask=async id=>{if(!manager()||!confirm('Xóa công việc này?'))return;let r=await db.from('qlcv_tasks').delete().eq('id',id);if(r.error)alert(r.error.message);else await load()};
$('loginTab').onclick=()=>switchMode('login');$('signupTab').onclick=()=>switchMode('signup');function switchMode(x){mode=x;$('loginTab').classList.toggle('active',x==='login');$('signupTab').classList.toggle('active',x==='signup');$('nameBox').classList.toggle('hidden',x!=='signup');$('authBtn').textContent=x==='signup'?'Tạo tài khoản':'Đăng nhập';$('authMsg').textContent=''}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authBtn').disabled=true;try{let email=$('email').value.trim(),pass=$('password').value;if(mode==='signup'){let r=await db.auth.signUp({email,password:pass,options:{data:{full_name:$('name').value.trim()}}});if(r.error)throw r.error;$('authMsg').textContent=r.data.session?'Tạo tài khoản thành công.':'Đã đăng ký, hãy xác nhận email rồi đăng nhập.';if(r.data.session)await load()}else{let r=await db.auth.signInWithPassword({email,password:pass});if(r.error)throw r.error;await load()}}catch(e){$('authMsg').textContent=e.message}finally{$('authBtn').disabled=false}};
$('reset').onclick=async()=>{let e=$('email').value.trim();if(!e)return $('authMsg').textContent='Nhập email trước.';let r=await db.auth.resetPasswordForEmail(e,{redirectTo:location.href});$('authMsg').textContent=r.error?r.error.message:'Đã gửi hướng dẫn đặt lại mật khẩu.'};
$('logout').onclick=async()=>{await db.auth.signOut();showAuth()};$('refresh').onclick=load;['search','status','priority'].forEach(id=>$(id).oninput=renderTasks);
$('saveProfile').onclick=async()=>{let r=await db.from('qlcv_profiles').update({full_name:$('pName').value.trim(),unit:$('pUnit').value.trim(),phone:$('pPhone').value.trim(),updated_at:new Date().toISOString()}).eq('id',user.id);if(r.error)alert(r.error.message);else{me={...me,full_name:$('pName').value.trim(),unit:$('pUnit').value.trim(),phone:$('pPhone').value.trim()};render();alert('Đã lưu hồ sơ')}};
$('newTask').onclick=()=>{if(!manager())return;$('tAssignee').innerHTML=people.filter(p=>p.role!=='Chỉ xem').map(p=>'<option value="'+p.id+'">'+esc(p.full_name)+(p.unit?' – '+esc(p.unit):'')+'</option>').join('');$('taskForm').reset();$('modal').classList.remove('hidden')};$('cancel').onclick=()=>$('modal').classList.add('hidden');
$('taskForm').onsubmit=async e=>{e.preventDefault();let r=await db.from('qlcv_tasks').insert({title:$('tTitle').value.trim(),description:$('tDesc').value.trim(),assignee_id:$('tAssignee').value||null,created_by:user.id,due_date:$('tDue').value||null,priority:$('tPriority').value,task_group:$('tGroup').value});if(r.error)alert(r.error.message);else{$('modal').classList.add('hidden');await load()}};
$('uProgress').oninput=()=>{$('uLabel').textContent=$('uProgress').value+'%'};$('uCancel').onclick=()=>$('updateModal').classList.add('hidden');
$('updateForm').onsubmit=async e=>{e.preventDefault();let id=$('uId').value,progress=+$('uProgress').value,status=$('uStatus').value;let r=await db.from('qlcv_tasks').update({progress,status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)alert(r.error.message);else{let x=await db.from('qlcv_task_updates').insert({task_id:id,updated_by:user.id,progress,status,note:$('uNote').value.trim()});if(x.error)console.warn(x.error);$('updateModal').classList.add('hidden');await load()}};
load();